name: target-check-1
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: none
  issues: read
  pull-requests: write

jobs:
  testing-secrets:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: execute
        run: bash .github/workflows/scripts/script.sh
